### ISSUE TITLE
Rendering with EGL seems to be non-deterministic

### ISSUE THREAD

**Issue by 1nadequacy** [deepmind/dm_control#100]
I'm observing a non-deterministic behavior when using pixels observations. I render with EGL and for two different runs of the same training code (with properly set seeding) I receive different pixels representations for the exactly same environment state.
The difference comes from values of individual pixels, for example in one case the pixels' value is 100, while in another 99.

**Comment by alimuldal** [comment]
This probably depends on your hardware and drivers, but in general I don't think you can rely on the output of the renderer to be perfectly deterministic. One possible reason why you might get slightly different output across runs is [temporal antialiasing][txaa], which you might be able to disable via a driver setting. I'm not sure there's much we can do about it at our end, though.

[txaa]: https://en.wikipedia.org/wiki/Temporal_anti-aliasing
