### ISSUE TITLE
ubuntu 18 dm_control.viewer error

### ISSUE THREAD

**Issue by adol001** [deepmind/dm_control#104]
I have installed dm_control in ubuntu 18.04, but I can't use viewer, other parts seem ok
`  File "/home/adol/anaconda3/lib/python3.6/site-packages/dm_control/viewer/gui/__init__.py", line 35, in ErrorRenderWindow
    'Cannot create a window because no windowing system could be imported')
ImportError: Cannot create a window because no windowing system could be imported`

I have installed current nvidia driver, and other dependency (sudo apt install libglfw3 libglew2.0 libgl1-mesa-glx libosmesa6)

**Comment by adol001** [comment]
I have a successful installation on ubuntu 16.04, on ubuntu 18.04, there is a bug in glew or linux, you can fix it by appending  "fs.inotify.max_user_watches=32768" to /etc/sysctl.d/99-sysctl.conf, the default is smaller than ten thousands

**Comment by DanielTakeshi** [comment]
@adol001  Thanks, is it OK to show your `/etc/sysctl.d/99-sysctl.conf` file? Did you just add that line at the  bottom?

**Comment by adol002** [comment]
> @adol001 Thanks, is it OK to show your `/etc/sysctl.d/99-sysctl.conf` file? Did you just add that line at the bottom?

I am adol001, yes

**Comment by adol002** [comment]
> @adol001 Thanks, is it OK to show your `/etc/sysctl.d/99-sysctl.conf` file? Did you just add that line at the bottom?

I am adol001, yes, just add that line.
