### ISSUE TITLE
How to build it on windows64?

### ISSUE THREAD

**Issue by Curry30h** [deepmind/dm_control#107]

**Comment by saran-t** [comment]
Closing this long-standing (sorry!!) issue, but as of today I've successfully installed the latest dm_control on win64 via `pip install --user git+https://github.com/deepmind/dm_control` after following the MuJoCo 2.1.1 installation instructions in the dm_control README file. (PyPI wheel will be updated shortly too, when that happens you will be able to `pip install dm_control`).
