### ISSUE TITLE
How to get geom_names from FieldIndexer?

### ISSUE THREAD

**Issue by gsp-27** [deepmind/dm_control#116]
Hi,
First a big thanks for this amazing python interface to mujoco.

My question is how do I get positions of particular ```geoms``` out of ```geom_xpos```.  So if I do ```physics.named.data.geom_xpos``` it returns a ```FieldIndexer``` to me. It contains positions of all the geoms with respect to world, now I want to get positions of some particular geoms.

Is there a way to iterate over this ```FieldIndexer``` and filter based on ```geom_names```?

**Comment by alimuldal** [comment]
This is mostly explained in Section 5 of our [tech report].

`FieldIndexer` supports an overloaded version of numpy's array indexing syntax. As well as integers, integer/boolean arrays, and slices, you can also use strings to address rows and/or columns in the array by name. For example:
```python
In [1]: from dm_control import suite
In [2]: env = suite.load('humanoid', 'run')
In [3]: env.physics.named.data.geom_xpos
Out[3]:
FieldIndexer(geom_xpos):
                      x         y         z
 0            floor [ 0         0         0       ]
 1            torso [ 0         0         1.5     ]
 2      upper_waist [-0.01      0         1.38    ]
 3             head [ 0         0         1.69    ]
 4      lower_waist [-0.01      0         1.24    ]
 5             butt [-0.0293    0         1.07    ]
 6      right_thigh [-0.00766  -0.095     0.865   ]
 7       right_shin [-0.0046   -0.09      0.482   ]
 8 right_right_foot [ 0.0323   -0.12      0.242   ]
 9  left_right_foot [ 0.0323   -0.08      0.242   ]
10       left_thigh [-0.00766   0.095     0.865   ]
11        left_shin [-0.0046    0.09      0.482   ]
12   left_left_foot [ 0.0323    0.12      0.242   ]
13  right_left_foot [ 0.0323    0.08      0.242   ]
14  right_upper_arm [ 0.08     -0.25      1.48    ]
15  right_lower_arm [ 0.27     -0.26      1.47    ]
16       right_hand [ 0.36     -0.17      1.56    ]
17   left_upper_arm [ 0.08      0.25      1.48    ]
18   left_lower_arm [ 0.27      0.26      1.47    ]
19        left_hand [ 0.36      0.17      1.56    ]
In [4]: env.physics.named.data.geom_xpos[['torso', 'left_hand']]  # This...
Out[4]:
array([[0.  , 0.  , 1.5 ],
       [0.36, 0.17, 1.56]])
In [5]: env.physics.named.data.geom_xpos[[1, 19]]  # ...is equivalent to this.
Out[5]:
array([[0.  , 0.  , 1.5 ],
       [0.36, 0.17, 1.56]])
```
For some fields the columns are also addressable by name. For example in this case you can use `geom_xpos['torso', 'x']` to get the x-coordinate of the torso.

If you're interested in the names themselves, one way to get them is via the `.axes` attribute, e.g.:
```python
In [6]: env.physics.named.data.geom_xpos.axes.row.names
Out[6]:
['floor',
 'torso',
 'upper_waist',
 'head',
 'lower_waist',
 'butt',
 'right_thigh',
 'right_shin',
 'right_right_foot',
 'left_right_foot',
 'left_thigh',
 'left_shin',
 'left_left_foot',
 'right_left_foot',
 'right_upper_arm',
 'right_lower_arm',
 'right_hand',
 'left_upper_arm',
 'left_lower_arm',
 'left_hand']
```
Another way is to iterate over the geom IDs (indices) and call `model.id2name`, e.g. `[env.physics.model.id2name(i, 'geom') for i in range(env.physics.model.ngeom)]`.

Note that names are optional for most MuJoCo elements. All of the models in the Control Suite have named geom elements, but this won't necessarily be true for MuJoCo XML files from other sources.

[tech report]: https://arxiv.org/abs/1801.00690
