### ISSUE TITLE
Configuring dm_control GPU rendering on Different GPUs

### ISSUE THREAD

**Issue by wilson1yan** [deepmind/dm_control#118]
Is there anyway to tell dm_control to render on a specific GPU? When I have many environments in parallel, they all render on GPU 0, and I'd like them to be evenly distributed across every GPU.

**Comment by saran-t** [comment]
If you're using our EGL context, you should be able to modify it to do this. The relevant code is here: https://github.com/deepmind/dm_control/blob/master/dm_control/_render/pyopengl/egl_renderer.py#L47

Currently, the implementation looks for the first device on which it can create and initialize an EGL display. You'll want to replace this with your own logic to distribute across multiple devices.

**Comment by alimuldal** [comment]
Currently we select and initialize only a single display device at import time, which is then shared by all `Physics` instances created in the same process. I think it should be relatively easy to add a way to control which GPU to select by modifying the code @saran-t  linked to, but distributing rendering contexts across multiple different devices would add a fair bit of complexity for what seems like quite a niche use-case. One compromise would be to split your environments across multiple processes, and select a different GPU per process.

Are you sure that rendering is the bottleneck, though? If you've got a decent GPU and you're only using it for rendering MuJoCo scenes (and not for training or inference) then I suspect you're probably more likely to hit CPU or memory constraints before you're able to saturate the GPU.

**Comment by astooke** [comment]
Wasn't sure a straightforward way to pass the device number as an input to environment initialization (maybe there is a way?), so using an environment variable and it works :)

replacing the `for device in EGL.eglQueryDevicesEXT():` line with:
```python
devices = EGL.eglQueryDevicesEXT()
if os.environ.get("EGL_DEVICE_ID", None) is not None:
  devices = [devices[int(os.environ["EGL_DEVICE_ID"])]]
for device in devices:
  ...
```

**Comment by astooke** [comment]
...should say, happy to do a little PR with this or something with more checks in it, if that's of interest?
