### ISSUE TITLE
RuntimeWarning: invalid value encountered in add

### ISSUE THREAD

**Issue by gsp-27** [deepmind/dm_control#138]
Hi,

When I load the environment ```lqr```. Since the action bounds are ```[-inf, inf]```, the code in ```dm_control/viewer/runtime.py:line 72``` gives me the above error.

Now this error is occurring because two infinite values are being added at that line. Is this expected behavior? if not I can try to submit a pull request which fixes it.

**Comment by paksas** [comment]
Hello,

This is just a warning The code calculates the correct value of bounds.

Best regards,
Piotr Trochim
