### ISSUE TITLE
Pixel wrapper not copied. Missing __init__.py?

### ISSUE THREAD

**Issue by martinseilair** [deepmind/dm_control#14]
I installed dm_control like suggested via pip. Unfortunately the dm_control/suite/wrappers folder was not copied by the setup. I guess the init file is missing.

**Comment by martinseilair** [comment]
There is also a small typo in the tech report on page 9. The named argument should be _pixels_only_ not _pixel_only_.

**Comment by yotam** [comment]
Thanks, this will be fixed in the next push.

**Comment by alimuldal** [comment]
Fixed in 40d8cf13bd91b2da43c5cecedcabc8e794f7febd
