### ISSUE TITLE
Availability on Linux Mint 19.2 (Tina)?

### ISSUE THREAD

**Issue by andreasbinder** [deepmind/dm_control#144]
I was wondering whether I can use dm-control on my plattform although it is not regularly tested? In specific, do you know links of ported repositories in case this one doesn't work? Thanks a lot!

**Comment by alimuldal** [comment]
We've never tested on Mint, but I'm not aware of any particular reason why `dm_control` wouldn't work on that distro. It's possible that some of the package dependencies mentioned in the Rendering section of the installation instructions are named differently compared to Ubuntu, but other than that I'd expect it to just work. Have you tried installing it?

**Comment by andreasbinder** [comment]
Seems to work!
