### ISSUE TITLE
Initialization the soccer environment for each episode

### ISSUE THREAD

**Issue by Takash7** [deepmind/dm_control#146]
I want to fix the position and velocity of the agent and the position and velocity of the ball when initializing the episode.
Which file should be rewritten and how should it be rewritten?

**Comment by alimuldal** [comment]
These are the relevant methods: https://github.com/deepmind/dm_control/blob/master/dm_control/locomotion/soccer/initializers.py#L56-L74

You could subclass `UniformInitializer` and override them to set the positions and velocities of the ball and the players however you like. An `Initializer` instance can be passed as an optional constructor argument to the `Task`: https://github.com/deepmind/dm_control/blob/master/dm_control/locomotion/soccer/task.py#L48
