### ISSUE TITLE
seet the mainplot env's time_limation

### ISSUE THREAD

**Issue by ChenyangRan** [deepmind/dm_control#150]
Hi, could you please tell me how to control the mainplot env, such as the suit env?
It seems the only thing I can set is the seed.
Can I seet the time_limitations such as suit_env?

**Comment by alimuldal** [comment]
You can override the time limit via the `task_kwargs` argument to `suite.load`, e.g.
```python
# Set the time limit to 5 seconds (the default for this environment is 10)
env = suite.load('cartpole', 'swingup', task_kwargs=dict(time_limit=5.))
```
