### ISSUE TITLE
SegFault on loading an environment

### ISSUE THREAD

**Issue by HenryZhou7** [deepmind/dm_control#16]
'''
>>> from dm_control import suite
>>> env = suite.load(domain_name='cartpole', task_name='swingup')
Segmentation fault (core dumped)
'''

I can import a suite but cannot load a testing environment.

**Comment by wookayin** [comment]
#2

**Comment by saran-t** [comment]
Since you didn't provide your system spec here, I am going to assume that this is a duplicate of #2. Please try the workaround suggested there, and provide us with further comments if it doesn't work.
