### ISSUE TITLE
Viewer for general purpose interactive rendering

### ISSUE THREAD

**Issue by kracon7** [deepmind/dm_control#163]
Hi,
Thanks for sharing this awesome repo. I have a question about the viewer for the environment. Is it limited to the environments provided in dm_control.suite? For example, if I have a custom environment that's not designed for control task, is there anyway to use the viewer for interactive rendering? 
Thanks in advance!

**Comment by alimuldal** [comment]
Hi,

The viewer can support custom environments provided that they implement the interface shown in [`dm_control.rl.control.Environment`](https://github.com/deepmind/dm_control/blob/master/dm_control/rl/control.py#L28). As well as the methods required by the `dm_env.Environment` interface (`.step`, `.reset` etc.), the environment must also expose a `.physics` attribute that exposes the underlying MuJoCo simulation (we can only support environments that are based on the `dm_control` MuJoCo bindings).

Environments based on [`dm_control.composer.Environment`](https://github.com/deepmind/dm_control/blob/master/dm_control/composer/environment.py#L266) will also work, for example see [`dm_control.manipulation.explore`](https://github.com/deepmind/dm_control/blob/master/dm_control/manipulation/explore.py), [`dm_control.locomotion.examples.explore`](https://github.com/deepmind/dm_control/blob/master/dm_control/locomotion/examples/explore.py).

Hope that helps.
