### ISSUE TITLE
Out-of-date pip version of `dm_control` causes the `tutorial.ipynb` to fail

### ISSUE THREAD

**Issue by kylevedder** [deepmind/dm_control#169]
If I install `dm_control` via pip, it installs version `0.0.322773188` (from `!pip show dm_control`) which is missing a `.matrix` field in `mujoco.Camera` which causes the `tutorial.ipynb` section _Projecting from world to camera coordinates_ to fail; however, if `dm_control` is installed from source, installing version `0.0.355168290`, the `.matrix` field is available.

**Comment by alimuldal** [comment]
Hi, thanks for the heads up. I've just uploaded new wheels, and I've confirmed that section of the tutorial notebook now works.
