### ISSUE TITLE
Is it possible to get running on M1 MacBooks?

### ISSUE THREAD

**Issue by slerman12** [deepmind/dm_control#180]

**Comment by saran-t** [comment]
Unfortunately MuJoCo doesn't currently provide an ARM binary. You could try and ask Roboti for this. (dm_control itself is pure Python so it should work on any platform.)

**Comment by jrabary** [comment]
Roboti is the weak point of the research in reinforcement learning.

**Comment by geyang** [comment]
Looks like these guys have it working? https://github.com/openai/gym/issues/2114

**Comment by geyang** [comment]
This is another related thread: https://www.reddit.com/r/reinforcementlearning/comments/kd6j0o/installing_openai_gym_on_an_m1_macbook/
