### ISSUE TITLE
How to use an image as background?

### ISSUE THREAD

**Issue by mhdhdri** [deepmind/dm_control#182]
I want to change the background and grid floor to other images and eventually play video in the background. Any ideas on how can this be done?

**Comment by yuvaltassa** [comment]
Like this?
https://twitter.com/rico_jski/status/1349032059680006144

https://arxiv.org/abs/2101.02722

Here is
<https://github.com/google-research/google-research/blob/master/distracting_control/background.py#L237>
how you upload textures.

Dr. Yuval Tassa | Research Scientist | Google DeepMind | ***@***.***

**Comment by mhdhdri** [comment]
Yes!
This seems to be what I want. Thanks.
