### ISSUE TITLE
Difference in environment rendering between dm_control and gym

### ISSUE THREAD

**Issue by ArgyChris** [deepmind/dm_control#184]
Hello!
I am trying to compare the reacher in dm_control against the default reacher in gym (Reacher-v2) 
When I render the observations to an image, their colors are different, lighter for dm_control (top image), and darker for the default gym (bottom image). 
I used gym's reacher.xml to configure dm_control's environment to be the same and have a common appearance,
 however it seems that there is another factor that determines how the images will appear, something like a default
 background lighting.
Is there something that I am missing?
Thank you
![DM_control_output](https://user-images.githubusercontent.com/51006386/118280196-a4730580-b4d4-11eb-9178-7b7498c06ba8.jpg)
![Learner_output](https://user-images.githubusercontent.com/51006386/118280221-a9d05000-b4d4-11eb-904d-e02b369474de.jpg)

**Comment by ArgyChris** [comment]
It seems that there is an extra lighting source somewhere in the .xml that I missed

**Comment by alimuldal** [comment]
It's a bit hard to diagnose without seeing any code. Are you including [`suite/common/visual.xml`](https://github.com/deepmind/dm_control/blob/master/dm_control/suite/common/visual.xml) in your XML? That defines a headlight that could account for the lighting difference.

**Comment by ArgyChris** [comment]
Hello, thank you for the reply. The problem was that I didn't include the visual.xml information that, as you said, defines some specifics for the lighting.
