### ISSUE TITLE
segmenting rendered mujoco env

### ISSUE THREAD

**Issue by mhdhdri** [deepmind/dm_control#188]
In mujoco envs, I want to know which pixels of rendered image belong to the robot. A bounding box can help too. 
Also, I've seen [this](https://github.com/openai/mujoco-py/pull/537) in mujoco-py but I'm not sure it is what I want and I don't know how to use it.
Can anybody help?

**Comment by alimuldal** [comment]
You can use [`render(..., segmentation=True)`](https://github.com/deepmind/dm_control/blob/master/dm_control/mujoco/engine.py#L192) for this. There's an example in our [tutorial notebook](https://colab.research.google.com/github/deepmind/dm_control/blob/master/tutorial.ipynb) under the "Rendering options" section.
