### ISSUE TITLE
Why state and observation in Control Suite have different dimensions?

### ISSUE THREAD

**Issue by ZJP-c4cld** [deepmind/dm_control#190]
I read the "dm_control: Software and Tasks for Continuous Control". In section 6.2 Domains and Tasks, I notice that state and observation in Control Suite have different dimensions. It makes me a little confused. In my understanding, observation is the partial version of state.(Agents may be unable to get global state because of some factors such as fog of war.) The dimension of state should be the same as the one of observation.
![image](https://user-images.githubusercontent.com/19870128/123724638-41d89c00-d8bf-11eb-8211-43f3a9918fdb.png)

**Comment by yuvaltassa** [comment]
The state is the low-level MuJoCo state (position+velocity), observations
are some function of this state.
For example the pendulum and acrobot have 1 and 2 angles (and corresponding
angular velocities) respectively, but in the observation dict the angles
are split into sin/cos
<https://github.com/deepmind/dm_control/blob/master/dm_control/suite/acrobot.py#L111>,
to account for the periodicity.

Dr. Yuval Tassa | Research Scientist | Google DeepMind | ***@***.***

**Comment by ZJP-c4cld** [comment]
@yuvaltassa Thank you for your prompt reply and selfless help ^_^
