### ISSUE TITLE
Are there any well_trained dm_control suite envs repo or pakage?

### ISSUE THREAD

**Issue by YuheGong** [deepmind/dm_control#191]
hi, everyone here. it is not exactely an issue, i am just wondering, is there any well_trained dm_control suite models? with reinforcement learning algorithms or any algorithms. i am trying to train ball_in_cup env for my project recently. and find nothing well_trained online.

**Comment by alimuldal** [comment]
`dm_control` is just intended to be a collection of environments and associated tools. We have no plans to distribute pretrained policies as part of this package.
