### ISSUE TITLE
Fast calculation of bounded quaternion distance

### ISSUE THREAD

**Issue by vaxenburg** [deepmind/dm_control#197]
I think there's a faster way of doing this calculation:
https://github.com/deepmind/dm_control/blob/master/dm_control/locomotion/tasks/reference_pose/rewards.py#L26

The bounded distance can be computed with a one-liner `np.arccos(2 * np.sum(quat1 * quat2)**2 - 1)` where `quat1`, `quat2` are (4,) arrays assumed to be unit quaternions.

I timed about a factor of 20 speedup with this one.

Also, the returned distance will be 2x larger than in the original function because, in fact, the original function computes half-angle.

**Comment by alimuldal** [comment]
Hi, thanks for the suggestion - do you want to send us a PR?

**Comment by vaxenburg** [comment]
Hi @alimuldal, sure, I'll prepare a PR soon

**Comment by vaxenburg** [comment]
It doesn't really matter anymore, but another problem with the previous implementation was that is was calling `tr.quat_dist` twice: once to get `default_dist` and once to get `anti_dist`. It's actually sufficient to call `tr.quat_dist` only once to get `default_dist` and then get `anti_dist` simply by `anti_dist = np.pi - default_dist`. This would have been a 2x speedup already.

**Comment by alimuldal** [comment]
True, and you could also get the minimum distance using `default_dist % np.pi`. I think there's other low-hanging fruit for optimization in the `transformations` library. Thanks again for contributing!

**Comment by vaxenburg** [comment]
I'll take a look, maybe I'll spot something to improve there:)
