### ISSUE TITLE
Hardware accelerated rendering on TPUs

### ISSUE THREAD

**Issue by ankeshanand** [deepmind/dm_control#212]
Hi,
I am trying to use Cloud TPUs and rendering seems to be the bottleneck b/c the it is not hardware accelerated. Is there a way to use EGL for rendering on TPUs?

**Comment by yuvaltassa** [comment]
Hi Ankesh,

No. TPUs do not support rendering.

Dr. Yuval Tassa | Research Scientist | Google DeepMind | ***@***.***
