### ISSUE TITLE
AttributedError when run bash scripts/run.sh

### ISSUE THREAD

**Issue by RainySun-GT** [deepmind/dm_control#219]
when i run the command "bash scripts/run.sh", i got the following error:

AttributeError: ~/.mujoco/mujoco210/bin/libmujoco210.so: undefined symbol: mj_certQuestion

how can i fix it?
Thanks a lot. I'm looking forward to your reply.

**Comment by saran-t** [comment]
This most likely means that you're running an old version of `dm_control`. Could you please try again with the latest version?

**Comment by RainySun-GT** [comment]
Oh, it works. The latest version can be installed by:
`pip install git+git://github.com/deepmind/dm_control.git`

Thank you for the timely reply.
