### ISSUE TITLE
Editable Mode Installation `ImportError`

### ISSUE THREAD

**Issue by kevinzakka** [deepmind/dm_control#238]
The installation fails with `pip install -e .` with the newest Mujoco 2.1.1 release. Script to reproduce:
```bash
git clone git@github.com:deepmind/dm_control.git
cd dm_control
pip install -e .
python -c "from dm_control import composer"
```

Note it works with `pip install git+git://github.com/deepmind/dm_control.git`.

**Comment by saran-t** [comment]
We don't really support editable/in-place installation for `dm_control`. What's happening is that our install command runs a custom `build_mjbindings` command (see setup.py) which generates ctypes bindings for MuJoCo functions and types.

It seems that when running `pip install -e .` these files aren't being generated at all. The closest you can get to in-place installation would be to run `pip install .` (without the `-e`), then symlink the generated files in `build/lib/dm_control/mujoco/wrapper/mjbindings` directory to the dm_control source tree. This way you'd be able to edit dm_control code in-place.

If you find a good way to integrate proper in-place installation logic into our setup.py without breaking anything, please feel free to set in a pull request!
