### ISSUE TITLE
rendering not working on macOS for version 2.1.1

### ISSUE THREAD

**Issue by enajx** [deepmind/dm_control#239]
Following the readme steps (pip install from last commit) the library can be install, however it can not render despite glfw being installed and the library path being set. Running the sample script:

```
from dm_control import suite
from dm_control import viewer

env = suite.load(domain_name="humanoid", task_name="stand")
viewer.launch(env)
```

produces the following error:

```
dm.py 27 <module>
viewer.launch(env)

__init__.py 39 launch
app = application.Application(title=title, width=width, height=height)

application.py 187 __init__
self._window = gui.RenderWindow(width, height, title)

__init__.py 34 ErrorRenderWindow
raise ImportError(

ImportError:
Cannot create a window because no windowing system could be imported
```

Using python 3.9, intel-based Mac.
In the same setup, glfw can render mujoco environments using [mujoco-py](https://github.com/openai/mujoco-py) with mujoco version 2.1.0. So glfw installation seems to be fine. (mujoco-py is also broken for version 2.1.1, so right now there is no way of using mujoco on mac with version 2.1.1.).

**Comment by saran-t** [comment]
Thanks for reporting. This appears to be caused by my commit 73c31ac21d1214f0a2eadfc8540a7f76796955cc rather than a breakage in MuJoCo 2.1.1. I'll work on reverting the offending commit now.

**Comment by kevinzakka** [comment]
Thanks @saran-t , this seems to have fixed rendering GLFW issues on my mac :-)!

**Comment by enajx** [comment]
@saran-t I'm still getting the same initial issue with the new mujoco installation via pip 😢
