### ISSUE TITLE
Non-Markovian Environments

### ISSUE THREAD

**Issue by yueatsprograms** [deepmind/dm_control#242]
What's the recommended way to rewind a simulation environment back to its full state at some point? For example, the following code (in python, for a dmc2gym environment):
```
a = np.copy(env.physics.get_state())
b = env.step()[0]
env.physics.set_state(a)
c = env.step()[0]
```
would produce the same `b` and `c` for the cart-pole, but not for the pendulum. In other words, the pendulum environment is Non-Markovian. Do I need to save some other "hidden" states of the pendulum?

**Comment by yuvaltassa** [comment]
Could you please also save and set `env.physics.qacc_warmstart`?
This is a usually-unimportant "hidden state", the previous accelerations which are used to warmstart the solver. It only matters for exact bitwise equality or after integrating for long periods.
