### ISSUE TITLE
dm_control.rl.control.PhysicsError: Physics state is invalid. Warning(s) raised: mjWARN_BADQACC

### ISSUE THREAD

**Issue by gemcollector** [deepmind/dm_control#258]
I am running the task "dog-walk", and this error always happens in different training steps. This task should fix some bug?

**Comment by yuvaltassa** [comment]
Interesting. Could you try reducing the [physics timestep](https://github.com/deepmind/dm_control/blob/master/dm_control/suite/dog.xml#L6) (or possibly using `integrator="RK4"` if your code is somehow tied to the 5ms) and seeing if that solves it?

You are not doing anything wrong, timesteps are often chosen to be as large as possible (for speed) without leading to divergence (what you are seeing). I suppose that when we were training this env our agent was a bit less aggressive and we could get away with 5ms, but it looks like that might be too big.
