### ISSUE TITLE
the meaning of "action"

### ISSUE THREAD

**Issue by jiameij** [deepmind/dm_control#26]
in the following code:

env = suite.load('humanoid', 'run')
spec = env.action_spec()
env.reset()
for _ in range(1000):
    action = np.random.uniform(spec.minimum, spec.maximum, spec.shape)
    env.step(action)
    pixels = env.physics.render()

"action" is  a ndarray of float64, i want to know, what's the meaning of the numbers in action, it is the joints' position, orientation, velocity, rotation or something else? If i know the ndarray of action, how can i get the state in next time step?

thank in advance

**Comment by alimuldal** [comment]
Each element in the `action` array corresponds to an actuator in MuJoCo. These are ordered the same as in the corresponding model XML. The `action_spec` of the environment is created here: https://github.com/deepmind/dm_control/blob/c24ec9f5f3cb3c25c6571c89c9f60bf3350f5711/dm_control/mujoco/engine.py#L756
