### ISSUE TITLE
What's the difference between qfrc_applied and qfrc_passive?When i set the qfrc_passive of a slide joint to 15,the robot don't move,but if i set the qfrc_applied to 15,the robot will move quickly,why?

### ISSUE THREAD

**Issue by Uptomylimit** [deepmind/dm_control#269]
In every step,I set mjpassive callback like this:
`mujoco.wrapper.core.set_callback('mjcb_passive', my_callback(env.physics.model, env.physics.data))`

`def my_callback(mjmodel,mjdata):`
    `F = np.matrix([[0.0], [0.0], [0.0], [0.0], [0.0], [0.0], [0.0], [0.0], [0.0]])`
    `F += fluiddynamics_joint9_abs.dragforce_head_joint(env.physics, t)`
    `F += fluiddynamics_joint9_abs.dragforce_no1_joint(env.physics, t)`
    `F += fluiddynamics_joint9_abs.dragforce_no2_joint(env.physics, t)`
    `F += fluiddynamics_joint9_abs.dragforce_no3_joint(env.physics, t)`
    `F += fluiddynamics_joint9_abs.dragforce_no4_joint(env.physics, t)`
    `F += fluiddynamics_joint9_abs.dragforce_no5_joint(env.physics, t)`
   ` F += fluiddynamics_joint9_abs.dragforce_tail_joint(env.physics, t)`

    mjdata.qfrc_passive[0] += F[0,0]
    mjdata.qfrc_passive[1] += F[1,0]
    mjdata.qfrc_passive[2] += F[2,0]
    mjdata.qfrc_passive[3] += F[3,0]
    mjdata.qfrc_passive[4] += F[4,0]
    mjdata.qfrc_passive[5] += F[5,0]
    mjdata.qfrc_passive[6] += F[6,0]
    mjdata.qfrc_passive[7] += F[7,0]
    mjdata.qfrc_passive[8] += F[8,0]
    print("mjdata",mjdata.qfrc_passive)

And the result is like this:
`mjdata [ 3.99041754 15.25025445  5.15961426  5.29100649  4.91947889  6.10987817
  8.11888827  7.88103777  3.90188425]`
The second number is the passive force of the slide joint,nearly 15,but the robot don't move,why?
If i set the qfrc_applied to 15,the robot will move quickly,why?

**Comment by yuvaltassa** [comment]
It is not immediately obvious. I recommend inspecting `data->qfrc_unc` in order to understand the difference. This is the vector of all smooth dynamics forces. Both `qfrc_applied` and `qfrc_passive` are summed into `qfrc_unc`, which then leads to `qacc_unc`, the unconstrained acceleration. This should help you debug.
