### ISSUE TITLE
The reset process for each episode is very very slow.

### ISSUE THREAD

**Issue by Frank-Dz** [deepmind/dm_control#272]
I am using the soccer 2-vs-2 for training. I found the ```self.timestep = self.env.reset()``` process takes a long time after each epsiode. Any suggestion about that?

**Comment by Frank-Dz** [comment]
A similar problem is posted here: https://github.com/deepmind/dm_control/issues/132

I don't what do they mean by "simulation" is slow. For me, the simulation part (time.step()) is fast enough, but the machine almost gets stuck there when I try to reset.

I have 16 threads and 2 teams (4 agents) here. I am using Box robot to play football.

**Comment by AwesomeLemon** [comment]
Hi @Frank-Dz, were you able to figure out the solution to this issue?
