### ISSUE TITLE
Could you tell me which task this is?

### ISSUE THREAD

**Issue by slerman12** [deepmind/dm_control#280]
I saw this in the DrQV2 repo. Wondering which task it is: https://camo.githubusercontent.com/a6bafbb78a387c5270a5f2b27b2e2a546f21e76ca5681ec9c64b54bf978d6deb/68747470733a2f2f696d6775722e636f6d2f73444767526f732e676966

It looks like a claw task, but I don't see anything like it in the DeepMind Control Suite paper.

**Comment by yuvaltassa** [comment]
These tasks are [here](https://github.com/deepmind/dm_control/tree/master/dm_control/manipulation).

**Comment by slerman12** [comment]
Is it the manipulator task? I’m a bit confused by the separation. There’s the “suite” and then this other set of tasks. Are the APIs for loading the different suites/tasks the same?
