### ISSUE TITLE
libmujoco.so.2.1.1 mj_certQuestion

### ISSUE THREAD

**Issue by delkov** [deepmind/dm_control#289]
I downlaod & extract mujoco 2.1.1;
Install dm_control by chnaging setup.py:  'dm-control==0.0.364896371',
Ubutnu 20.04, python 3.6.9

But I got error..
AttributeError: /home/delkov/.mujoco/lib/libmujoco.so.2.1.1: undefined symbol: mj_certQuestion

**Comment by kevinzakka** [comment]
Any reason you're trying to install 2.1.1? I'd just go for the latest dm_control (1.0.2) and mujoco (2.1.5) which you can install with `pip install --upgrade dm_control`.
