### ISSUE TITLE
Mujoco install automatic?

### ISSUE THREAD

**Issue by slerman12** [deepmind/dm_control#291]
It's been a while since I checked in here. From the looks of the readme, it seems like there are a lot fewer steps tp getting this running. Is the mujoco install now automatic?

**Comment by kevinzakka** [comment]
Yes, it gets automatically installed as seen [here](https://github.com/deepmind/dm_control/blob/main/setup.py#L190).

**Comment by slerman12** [comment]
Awesome! Will this work on Mac too? I was previously getting an egl error when running on Mac.

**Comment by kevinzakka** [comment]
Works beautifully on mac :) It's wicked fast on M1s too

**Comment by saran-t** [comment]
EGL isn't supported on macOS, but CGL-based GLFW contexts should just work.

**Comment by slerman12** [comment]
Just checking, is GLFW slower than EGL? Since it's prioritized in the check to see which one is available, I'd assume it's the best and fastest. I know nothing about this.

I am testing my model on an M1 Mac and school Linux computers, so I find myself having to specify `MUJOCO_GL='egl' `environment variable every time I want to use the school nodes.

**Comment by saran-t** [comment]
I should've replied ages ago, but no the rendering speed should be the same between GLFW and EGL, but the latter is more likely to work unless you're working with a headless machine. (I'm uncertain if non-Nvidia GPUs support the EGL extension that we use for headless rendering).
