### ISSUE TITLE
how to load customized model from xml?

### ISSUE THREAD

**Issue by jinfagang** [deepmind/dm_control#293]
Hi, how to load customized model from xml?

**Comment by kevinzakka** [comment]
Can you be more specific? Do you mean you have an XML file path and you want to load the model?

**Comment by jinfagang** [comment]
@kevinzakka Hi, I just digged into issues and found a solution. But I found an issue about dm_control or maybe mujoco, Why does mujoco read xml file always need absolute path? that was weired.

it's maybe not mujoco, it's dm ctonrl issue:

```
from dm_control.suite import common
common.read_model(MODEL_XML_PATH), common.ASSETS

```

it will read model in asolute path, and all path inside xml, should be absolute, otherwise cause not found error. Why??

**Comment by kevinzakka** [comment]
You're using `suite` specific methods here. In general, you can just read an XML file using `mujoco` itself:

```python
import mujoco
mujoco.MjModel.from_xml_path(MODEL_XML_PATH)
```

and it doesn't require absolute paths for the meshes or textures.

**Comment by jinfagang** [comment]
thank u, I just fixed it.
