### ISSUE TITLE
CRITICAL:absl:Expired activation key

### ISSUE THREAD

**Issue by DexiongYung** [deepmind/dm_control#305]
I installed MuJoCo200 and it's key from https://roboti.us/index.html, because I'm using dmc2gym and I get the error `CRITICAL:absl:Expired activation key` and `dm_control.mujoco.wrapper.core.Error: Could not register license`. I'm installing on Ubuntu. I really have no idea why this is happening.

**Comment by vmoens** [comment]
Perhaps you have more than one key?
Have you tried setting `export MJKEY_PATH=path/to/.mujoco/some/custom/key.txt`?
