### ISSUE TITLE
Observation list 

### ISSUE THREAD

**Issue by AOS55** [deepmind/dm_control#313]
Does anyone happen to have a numbered list for the observation and actions found in the [control suite](https://github.com/deepmind/dm_control/blob/main/dm_control/suite/quadruped.py)?

Principally for reference thanks

**Comment by yuvaltassa** [comment]
This is easy to do in code:
```Python
env = suite.load('hopper', 'stand')
env.observation_spec()

OrderedDict([('position', Array(shape=(6,), dtype=dtype('float64'), name='position')), ('velocity', Array(shape=(7,), dtype=dtype('float64'), name='velocity')), ('touch', Array(shape=(2,), dtype=dtype('float64'), name='touch'))])
```

Is this what you want?
