### ISSUE TITLE
I want to tilt the mag in Python.

### ISSUE THREAD

**Issue by miyukin73** [deepmind/dm_control#318]
Hello,
I'd like to simulate tilting a cup with a ball in it.

Having been taught by [mujoco](https://github.com/deepmind/mujoco.git), 
I succeeded in tilting the cup directly with MuJoCo as shown in the video below.

https://user-images.githubusercontent.com/63595993/178091058-bb0f41e7-9b67-400d-972c-cb8b9929e72a.mp4

However, I'd like to do this through Python.
I've checked some of the code, but I'm a beginner and I'm not sure which program to use to start MuJoCo, which is why I asked the question.

Sorry for the trouble, but I'd like to know if there is a program that might be helpful in the simulation of tilting the cup.
Thank you in advance.

**Comment by yuvaltassa** [comment]
Check the basic colab mentioned in [Getting Started](https://github.com/deepmind/mujoco#getting-started).

To tilt the cup in exactly the same way, you can add a torque to `data.xfrc_applied`, or you can add an actuator that is attached to a site (a little bit like a rocket engine), and you can use the `gear` attribute to choose what kind of force/torque you want to apply.
