### ISSUE TITLE
custom fluid dynamics: debugging

### ISSUE THREAD

**Issue by ss555** [deepmind/dm_control#320]
I work on implementing a robotic fish simulator and **compare dynamics defined by mujoco and my own coded differential equations**. 
I wonder why the density of environment is 5000 in 
> https://github.com/deepmind/dm_control/blob/main/dm_control/suite/fish.xml

The basic workflow is that I import several .STL files as meshes in `fish.xml` file, and then I write custom dynamics equations in the Task(swim) class of in fish.py (which is I suppose is an analog of `mj_step1` of original mujoco callback)

```
def before_step(self, action, physics):
        with physics.reset_context():

            physics.named.data.qpos['slider'] = self.x 
            ...
```
Then the idea is that I code in python callback what was described.
> https://mujoco.readthedocs.io/en/latest/computation.html?highlight=fluid%20dynamics#passive-forces
I search for fluid dynamics model implementation in the **C source code**, but had some difficulties.

**p.s** suggestion: when I try to run a random policy, I have **dm_control.rl.control.PhysicsError: Physics state is invalid. Warning(s) raised: mjWARN_BADQACC** at the 1st timestep **WARNING:absl:Nan, Inf or huge value in QACC at DOF 0. The simulation is unstable. Time = 0.0010.** After logging, I found j2 joint acceleration is 145.81178703 too big, while 14.5 is fine, it would be nice to show the value as an error to the user.

**Comment by yuvaltassa** [comment]
There is no good reason why the density is 5000, these environments are not meant to be particularly realistic, this was a value for which the simulation looked good.

I would recommend using the implicit integrator if you are experiencing instabilities.

Did you have any other questions?

**Comment by ss555** [comment]
Thank you for your quick response, do you know where the passive forces (namely fluid dynamics) are implemented in the code?
> https://github.com/deepmind/mujoco

**Comment by yuvaltassa** [comment]
Sorry for delayed response, this is a question for the `mujoco` repo, not `dm_control`.

MuJoCo has **two** fluid models, see [here](https://github.com/deepmind/mujoco/blob/main/src/engine/engine_core_smooth.c#L1258). The ellipsoid-based model is much more powerful but not fully documented. Let us know if you need more help, but please do so in the `mujoco` repo.
