### ISSUE TITLE
Questions about "The first tutorial focuses on the basic MuJoCo Python bindings" in "Getting Started"

### ISSUE THREAD

**Issue by miyukin73** [deepmind/dm_control#322]
Hello,

I would like to simulate the attached XML file ([mug-xml_obj.zip](https://github.com/deepmind/dm_control/files/9098780/mug-xml_obj.zip)) in MuJoCo using Python (dm_control).

So I was trying "[The first tutorial focuses on the basic MuJoCo Python bindings](https://colab.research.google.com/github/deepmind/dm_control/blob/main/dm_control/mujoco/tutorial.ipynb)" in ["Getting Started"](https://github.com/deepmind/mujoco#getting-started),
which you summarized in an easy to understand way.

However, when I run the following program, MuJoCo does not start up, although there is no error.
```
static_model = '/home/user/anaconda3/envs/robot/mug.xml'"""
<mujoco>
  <worldbody>
    <light name="top" pos="0 0 1"/>
    <geom name="red_box" type="box" size=".2 .2 .2" rgba="1 0 0 1"/>
    <geom name="green_sphere" pos=".2 .2 .2" size=".1" rgba="0 1 0 1"/>
  </worldbody>
</mujoco>
"""
physics = mujoco.Physics.from_xml_string(static_model)
pixels = physics.render()
PIL.Image.fromarray(pixels)
```

![image](https://user-images.githubusercontent.com/63595993/178647137-3a396360-2ae5-468b-a781-7b3f1b8f06ec.png)
#
How should I deal with this in order to display the above screen?

I am very sorry for repeatedly asking you related questions, but I would appreciate your cooperation.

**Comment by yuvaltassa** [comment]
You want `from_xml_path` rather than `from_xml_string` if you want to load a model from file.
