### ISSUE TITLE
Wrong angles

### ISSUE THREAD

**Issue by Melanol** [deepmind/dm_control#331]
This is now my model looks in simulate:
![Screenshot from 2022-08-04 17-01-08](https://user-images.githubusercontent.com/33939307/182842107-5d2a7c61-70a3-4b74-93c2-33b6a8f999de.png)

This is how it looks when I import it with `mjcf.from_path("tripod.xml")` into the tutorial task:
![Screenshot from 2022-08-04 17-00-52](https://user-images.githubusercontent.com/33939307/182842348-8c7b3b2a-1b87-43ed-b891-fb0eda7b8a91.png)

**Comment by yuvaltassa** [comment]
This would be easier to diagnose if you included the actual XML. Off the top of my head I suspect the base arena in our `mjcf` tutorial sets `<compiler angle="radian"/>` somewhere, while your original uses degrees?

**Comment by Melanol** [comment]
@yuvaltassa I do use degrees in my .xml. I think you are right, I did
```
    model = mjcf.from_path("tripod.xml")
    model.compiler.angle = "degree"

    return model
```

and received

`ValueError: Conflicting values for attribute `angle`: radian vs degree`

So, what is the fix?

**Comment by Melanol** [comment]
OK, I manually changed all degrees in my .xml to radians, and it works.
