### ISSUE TITLE
Improve collision detection

### ISSUE THREAD

**Issue by jangirrishabh** [deepmind/dm_control#337]
Hi, any suggestions on how to improve the collision in this case. Refer Picture. The small boxes sometimes sneak out of the large containers. I suppose this is some constraint solver issue, but not sure what. 

For the smaller boxes I have condim=6, conaffinity=contype=1 and friction = (0.9, 0.005, 0.0001). The script for the large container boxes is below.

![Screenshot from 2022-08-19 12-22-45](https://user-images.githubusercontent.com/8028739/185694128-f0f8ac9a-e283-46c6-952c-bf6bfc70ab71.png)

Here's my partial script for the boxes.

`<mujoco model="standard_tote">
    <compiler angle="radian" />
    
    <visual>
      <global offheight="960" offwidth="1280"/>
    </visual>

    <default>
      
      <geom type="box" condim="4" density="10000"/>
      <default class="wall">
        <geom rgba=".5 .5 .5 1" condim="4" density="10000"/>
      </default>
    </default>

    <asset>
      <texture name="skybox" type="skybox" builtin="gradient" rgb1="0.7 0.7 0.7" rgb2="0.9 0.9 0.9" width="100" height="100"/>
        <mesh name="tote" file="tote.stl" />
    </asset>
    <worldbody>
      <body name="picking_tote" pos="-0.5 0 0" quat="0.7071068 0 0 0.7071068">
        <joint name="pick_tote"  axis="0 1 0" damping="1" limited="true" range="-0.001 0.001" frictionloss="1"/>
        <geom name="pick_tote_bottom" size=".6 .37 .02" pos="0 0 0" mass="30"/>
        <geom name="pick_tote_side1" size=".01 .35 .29" pos="-.6  0 .3" class="wall"/>
        <geom name="pick_tote_side2" size=".01 .35 .29" pos=".6 0 .3" class="wall"/>
        <geom name="pick_tote_side3" size=".6 .01 .29" pos="0 -.36 .3" class="wall"/>
        <geom name="pick_tote_side4" size=".6 .01 .29" pos="0 0.36 .3" class="wall"/>
      </body>

      <body name="packing_tote" pos="0.5 0 0" quat="0.7071068 0 0 0.7071068">
        <joint name="pack_tote"  axis="0 1 0" damping="1" limited="true" range="-0.001 0.001" frictionloss="1"/>
        <geom name="pack_tote_bottom" size=".6 .37 .01" pos="0 0 0" mass="30"/>
        <geom name="pack_tote_side1" size=".01 .35 .29" pos="-.6  0 .3" class="wall"/>
        <geom name="pack_tote_side2" size=".01 .35 .29" pos=".6 0 .3" class="wall"/>
        <geom name="pack_tote_side3" size=".6 .01 .29" pos="0 -.36 .3" class="wall"/>
        <geom name="pack_tote_side4" size=".6 .01 .29" pos="0 0.36 .3" class="wall"/>
      </body>
    </worldbody>
</mujoco>
`

**Comment by yuvaltassa** [comment]
Please attach loadable models so we can reproduce. A partial model is not helpful. Not being able to load your model (well I could load it after fixing it, but you included no objects), I can only guess how to help you.

My recommendations would be to
1. Use thicker walls.
2. Have full overlap between the box geoms at the joins (corners).
3. Enable the (experimental) `multiccd` option.
4. Decrease the timestep.
