### ISSUE TITLE
cannot open .stl mesh files

### ISSUE THREAD

**Issue by NgChucky** [deepmind/dm_control#338]
I tried to load this xml file in simulate.exe:
(my models are stored in the 'MuJoCo models' directory, including the stl file)
```
<mujoco> 
<compiler meshdir="C:/Users/Nagaraju Chukkala/Documents/programs/MuJoCo models/"/>  
    <worldbody>  
        <geom name='monkey' type="mesh" />  
    </worldbody>  
</mujoco>
```
It says "Error: mesh geom 'monkey' (id=0) must have valid meshid"
Also, where is the documentation for dm_control for python?

**Comment by yuvaltassa** [comment]
The mesh needs to referenced by a geom.

[Here](https://mujoco.readthedocs.io/en/latest/XMLreference.html) is the documentation.

**Comment by NgChucky** [comment]
Yuval Tassa! That's a privilege. I came here to close this issue as I had figured it, and saw Yuval's reply.
