### ISSUE TITLE
Batched Environments (2022)

### ISSUE THREAD

**Issue by proceduralia** [deepmind/dm_control#342]
Hello,

Thank you so much for your work on this! I read some previous discussion on the topic in this forum, but I'm not sure if batched environments (i.e., multiple copies of the same environment running in parallel with a single .step() call) is available through the new Mujoco version and/or whether it is already usable in dm_control itself.

That would be very useful to many!

Thank you,

Pierluca

**Comment by yuvaltassa** [comment]
Fully batched C++ environments (also exposed to Python) is a long term project we are working on right now. If all you need is batched physics steps, this is already available. See [here](https://mujoco.readthedocs.io/en/latest/python.html#code-sample-open-loop-rollout) and [here](https://github.com/deepmind/mujoco/blob/main/python/mujoco/rollout_test.py#L264) for details.

If you need a batched C++ environment and don't want to wait for our solution, we can recommend [envpool](https://github.com/sail-sg/envpool).
