### ISSUE TITLE
How to measure acceleration values of each moving objects?

### ISSUE THREAD

**Issue by miyukin73** [deepmind/dm_control#354]
Hi, 

I want to get the each acceleration values of some moving objects.

When we get the position and velocity, we use `data.xpos`, `data.qpos`, `data.qvel`,

but how about the acceleration??

Is it possible to get the values?

Thank you in advance.

**Comment by yuvaltassa** [comment]
[mj_objectAcceleration](https://mujoco.readthedocs.io/en/latest/APIreference.html#mj-objectacceleration)
