### ISSUE TITLE
Reward function returning 'Nonetype'

### ISSUE THREAD

**Issue by anonlinear** [deepmind/dm_control#36]
Hi!
I am running the 'swingup' task under the 'acrobot' model. I am randomly sampling a set of action inputs and evaluating the rewards.  For some action inputs, I am getting a reward output of 'Nonetype'. So when I try to add the total reward I get the following exception
 trew+=time_step.reward

TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType

Has anyone else encountered this issue? Is there a way to resolve this?

**Comment by Jin0932** [comment]
Today ,I meet the question the same to you, Could you tell me what your methods to solve, thanks!
