### ISSUE TITLE
[Basic Question] what is the unit of "data.qvel"

### ISSUE THREAD

**Issue by miyukin73** [deepmind/dm_control#362]
Hello, 
I use "data.qvel" and rotate the cup as bellow.
```
for i in range(t3+2):
    data.qvel[0] = 3
```
![rotate0_0_0_a0 7_b0 7_c0 0075](https://user-images.githubusercontent.com/63595993/203505563-df09aa58-14fb-4eaf-92c7-380e48466907.gif)

However, I don't know about the **unit** of `data.qvel`.

Is this 3 **[deg/s]**, 3 **[rad/s]** or other??

Also, is there another appropriate way to write a program to rotate an object?

Sorry for a basic question.

Thank you.

**Comment by yuvaltassa** [comment]
For hinges and ball DoFs, rad/s. For slider DoF length unit/s.

**Comment by miyukin73** [comment]
Thank you very much.
