### ISSUE TITLE
what does "mean return" mean in the tech report?

### ISSUE THREAD

**Issue by adwardlee** [deepmind/dm_control#37]
Hi, 

Does it mean the reward of every episode? Besides, is it normal that ddpg algorithm can only successfully learn how to stand in the humanoid run environment given different seeds? Thanks.

**Comment by alimuldal** [comment]
There is some explanation on page 13 of the tech report:

> In the state feature case we ran 15 different seeds for each task with A3C and DDPG; for results with D4PG, which was generally found to be more stable, we ran 5 seeds. In the raw-pixel case we also ran 5 different seeds for each task. The seed sets the network weight initialisation for the associated run. In all cases, initial network weights were sampled using standard TensorFlow initialisers. In the figures showing performance on individual tasks (Figures 4-7), the lines denote the median performance and the shaded regions denote the 5th and 95th percentiles across seeds. In the tables showing performance for individual tasks (Tables 1 & 2) we report means and standard errors across seeds.

Here, "performance" refers to the total reward per episode (the reward is between 0 and 1 per timestep, and there are always 1000 steps per episode). I believe "mean" refers to the fact that the learning curves were smoothed by computing the average reward per episode within a sliding window. Most DDPG seeds are able to learn humanoid:stand to some extent from features, although as mentioned in the text the final performance is not as good as D4PG, and there is a lot more variance across seeds.
