### ISSUE TITLE
Cannot see corridor side planes

### ISSUE THREAD

**Issue by RayYoh** [deepmind/dm_control#386]
When I set `visible_side_planes = True` in `corridor_arenas.EmptyCorridor(visible_side_planes = True)`, I still cannot see the planes when I render the environment. But if I modify
```
self._left_plane = self._mjcf_root.worldbody.add(
        'geom', type='plane', xyaxes=[1, 0, 0, 0, 0, 1], size=[1, 1, 1],
        rgba=[1, 0, 0, alpha], group=_SIDE_WALLS_GEOM_GROUP)
```
to
```
self._left_plane = self._mjcf_root.worldbody.add(
        'geom', type='plane', xyaxes=[1, 0, 0, 0, 0, 1], size=[1, 1, 1],
        rgba=[1, 0, 0, alpha])
```
I can see them. How can I tackle this problem?

**Comment by RayYoh** [comment]
By the way, is there any examples for this env used in [Emergence of Locomotion Behaviours in Rich Environments](https://arxiv.org/pdf/1707.02286.pdf)
![image](https://user-images.githubusercontent.com/35106336/224645131-7e2b9d3c-6444-4e78-8f05-c1b4a8defe43.png)

**Comment by yuvaltassa** [comment]
You need to turn on the visualisation of the geom group `_SIDE_WALLS_GEOM_GROUP`.

Something like 
```py
scene_option = mujoco.wrapper.core.MjvOption()
scene_option.geomgroup[_SIDE_WALLS_GEOM_GROUP] = True
pixels = physics.render(scene_option=scene_option)
```
