### ISSUE TITLE
soccer player doesn't move

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [deepmind/dm_control#391]
I run the simulator as follows:

```
python3 dm_control/dm_control/locomotion/soccer/explore.py
```
The image is as follows:

![Screenshot from 2023-03-24 17-30-56](https://user-images.githubusercontent.com/23301778/227467836-ae758d26-43ef-4702-a207-f94a94c30854.png)

But it didn't move at all.
Please let me know how to move the player.

**Comment by yuvaltassa** [comment]
You need to send actions to the environment.
Try to explore the code in dm_control to find examples of this.
