### ISSUE TITLE
question regarding segmentation map's values

### ISSUE THREAD

**Issue by hnyu** [deepmind/dm_control#395]
Hi,

I'm trying to use `Camera.render()` to render a segmentation map to check if an object is in a camera's view. I noticed that the segmentation map might contain very few incorrect geom id values on the border of an object. Below is an example (the segmentation maps are 64x64 but nearest-neighbor scaled for visibility):

![Screen Shot 2023-03-28 at 8 08 17 PM](https://user-images.githubusercontent.com/51248379/228416658-1c61cb57-23ab-4b82-a707-479922e09e48.png)

![Screen Shot 2023-03-28 at 8 08 25 PM](https://user-images.githubusercontent.com/51248379/228416673-57d16aa6-5be9-4d3b-82bd-8c55dfcd2d91.png)

Basically the first figure is the returned segmentation map, after mapping each geom id to a random color. The view is from a robot camera and the two vertical bars are its two grippers which we can ignore here. If we look at the "basket" on the ground we can see that there are  7 different colors (geom ids). However, the basket is expected to only have 5 geoms/colors (one bottom and four sides). 

The second figure is after I mapped the geom ids to their object indices, and we can see that there are four pixels at the bottom are thought to come from another object (behind the camera). 

This observation occurs even for higher-resolution maps, although in that case the incorrect geom id values are more difficult to be observable. For example, I found that someone else's result at https://github.com/openai/mujoco-py/issues/516 seems to also have this border issue. 

My question is, is this behavior expected? How is the segmentation map generated intuitively? 

(This issue is critical because I'd like to use a low resolution segmentation map to determine if an object is in the view, which is much more computationally efficient than a high resolution one. However, this border issue makes using small segmentation maps difficult.)

**Comment by yuvaltassa** [comment]
This is due to antialiasing being turned on during segmentation rendering. Of course it *should* be off, and indeed [this line](https://github.com/deepmind/mujoco/blob/2127d0bb3f1ab8c23b9e7799bfa3347ef85f9b62/src/render/render_gl3.c#L833) is supposed to turn it off for segmentation renders, but we have also noticed that this command is sometimes ignored by the GL backend. 

Could you try turning off antialiasing completely in your model by setting [offsamples](https://mujoco.readthedocs.io/en/latest/XMLreference.html#visual-quality-offsamples) to 1? (Or maybe 0, I'm actually not sure)?

**Comment by hnyu** [comment]
> This is due to antialiasing being turned on during segmentation rendering. Of course it _should_ be off, and indeed [this line](https://github.com/deepmind/mujoco/blob/2127d0bb3f1ab8c23b9e7799bfa3347ef85f9b62/src/render/render_gl3.c#L833) is supposed to turn it off for segmentation renders, but we have also noticed that this command is sometimes ignored by the GL backend.
> 
> Could you try turning off antialiasing completely in your model by setting [offsamples](https://mujoco.readthedocs.io/en/latest/XMLreference.html#visual-quality-offsamples) to 1? (Or maybe 0, I'm actually not sure)?

Setting offsamples to 0 indeed solved this problem (I also tried 1 and it seemed to be fine in my case but I'm not sure in general). I wonder if there is any better solution so that it won't affect the RGB frame? That is, we still have anti-aliasing for RGB/depth (buffers that usually have "continuous" values) but not for segmentation.

**Comment by hnyu** [comment]
> The correct solution is exactly the line I linked to above. This generally works, yet sometimes doesn't 🤷‍♂️
> 
> What GL backend are you using?

I'm using EGL as the backend.

**Comment by yuvaltassa** [comment]
Easiest to just create two `Physics`?

**Comment by hnyu** [comment]
> Easiest to just create two `Physics`?

I see. Thanks for the suggestion. I'll just turn off offsamples for now.
