### ISSUE TITLE
[Question] Computing the action jacobian of the dynamics (dF(x, a)/da) in dm_control environments?

### ISSUE THREAD

**Issue by biegunk** [deepmind/dm_control#397]
Other than manually implementing a finite-difference computation, is it possible to get the jacobian of the environment dynamics with respect to the action evaluated at a given state-action pair in the dm_control RL envionrments?

**Comment by yuvaltassa** [comment]
See [mjd_transitionFD](https://mujoco.readthedocs.io/en/latest/APIreference/APIfunctions.html#mjd-transitionfd)
