### ISSUE TITLE
pyproject.toml Out of Lockstep with Mujoco Versioning

### ISSUE THREAD

**Issue by bebark** [deepmind/dm_control#398]
Hi,

Just spent a couple hours resolving this for myself, so thought I should mention it here as well. When you all bump the dm_control versions up you also have been bumping the inequality for mujoco version in requirements.txt and setup.py, but not in pyproject.toml. 

As of right now requirements will not pull the most recent version and the other two will. You can reproduce my issue by pulling any one of the versioning update commits, like [this](https://github.com/deepmind/dm_control/tree/f3ae36a7a7d1aa139cda04956dffb6687c633743) one. When you pip install the build will 'succeed', but the bindings will be improperly built and fail the mjbindings_test. As far as I can tell this is because the build level and python env versions of mujoco will be different. 

Can you add the same equality constraint on mujoco that's in requirements.txt to pyproject.toml to make this more clear for backwards compatibility sake?

**Comment by bebark** [comment]
Actually upon further investigation even setting all three to equalities and version 2.3.4 doesn't work. I had to jump back to 2.3.3 for all three. So something else is going on too. But the issue still remains.

**Comment by saran-t** [comment]
@bebark 2.3.4 was a botched release that I've had to yank. The requirements.txt at head has been updated to `mujoco==2.3.5` but setup.py was left alone since it only specified `>=2.3.4`.

You're right in that I've neglected to bump up pyproject.toml for some time. Could you please try to see whether updating it to 2.3.5 resolves your issue?

**Comment by bebark** [comment]
So they just updated mujoco again to 2.3.6 yesterday, so 2.3.5 won't work unless I set setup.py, pyproject, and requirements all to be == to the same version (2.3.5, 2.3.6, 2.3.3, etc.). I think that is the resolution. If I leave pyproject without constraint that seems to always cause the binding generation errors.

**Comment by saran-t** [comment]
We have not "updated MuJoCo" to version 2.3.6. We only pre-bump the version number at head.

Users should not be building from head unless they need the development version for some specific reason. Released versions correspond to tagged commits on that repo per usual practice.

**Comment by saran-t** [comment]
Can you please post what the actual update you're getting is? There's no inconsistency between setup.py (`mujoco>=2.3.5`), requirements.txt (`mujoco==2.3.5`), and pyproject.toml (unconstrained), as far as I can tell.

**Comment by bebark** [comment]
Grabbing one of the tagged versions seems to fix my issue. Sorry for the trouble!
