### ISSUE TITLE
Roll out time

### ISSUE THREAD

**Issue by rajcscw** [deepmind/dm_control#40]
After using Open AI gym environments, I notice that wall clock time of a typical roll out is higher in this suite. Does it have to do something with rendering (though I'm not rendering the environment). This makes training time longer. 

Is there anything we should do to avoid rendering in the background and make it faster? Or env._sub_steps = 1 ?

Your inputs are highly appreciated.

**Comment by rajcscw** [comment]
Ok, yes, that makes sense! Thanks for your answer.

**Comment by alimuldal** [comment]
You can also set the time limit when you instantiate the environment, for example:

```python
# Default time limit is 10 seconds.
env = suite.load('cartpole', 'swingup', task_kwargs={'time_limit': 5})
```

**Comment by rajcscw** [comment]
Hi, @alimuldal, you mentioned that default time limit of each episode is 10 seconds. Is it equivalent to 1000 timesteps mentioned in https://arxiv.org/pdf/1801.00690.pdf ?
