### ISSUE TITLE
UI. A way to zero an actuator in simulate

### ISSUE THREAD

**Issue by Melanol** [deepmind/dm_control#404]
Not very important.

There is a "Clear all" button in simulate to zero all actuators, but I sometimes find it frustrating that there is no way to zero a particular actuator, and I have to try to click as close to 0 as possible, and it is not helpful, as even the smallest value results in movement. This would be useful for manual tests.

![Screenshot from 2023-06-18 11-49-12](https://github.com/deepmind/dm_control/assets/33939307/a8b20703-29ab-44f6-8c7c-a9679131786c)

**Comment by Melanol** [comment]
Wrong repo. It's for mujoco. Delete it maybe?

**Comment by yuvaltassa** [comment]
This is a nice feature request for mjUI. Double-clicking on a slider could reset it. But yes, wrong repo.
