### ISSUE TITLE
Question about the damping setting of joint

### ISSUE THREAD

**Issue by Uptomylimit** [deepmind/dm_control#413]
After reading your code and document, I am confused of the setting of the joint.
In cheetah.xml, the default joint is set as :

`<joint limited="true" damping=".01" armature=".1" stiffness="8" type="hinge" axis="0 1 0"/>`

In humaniod.cml, the default joint is set as :

```
<default class="body">
      <geom  type="capsule" condim="1" friction=".7" solimp=".9 .99 .003" solref=".015 1" material="self"/>
      <joint type="hinge" damping=".2" stiffness="1" armature=".01" limited="true" solimplimit="0 .99 .01"/>
      <default class="big_joint">
        <joint damping="5" stiffness="10"/>
        <default class="big_stiff_joint">
          <joint stiffness="20"/>
```

And there are many other examples you provide. So I am confused about how to choose these parameters for my robot? Is there any computation or estimation method for these parameters? Or is there any method for choosing these parameters?

**Comment by yuvaltassa** [comment]
Of course you can and should do sysID for real hardware.

[This docs section](https://mujoco.readthedocs.io/en/latest/modeling.html#solver-parameters) might be helpful.
