### ISSUE TITLE
How to get the velocity of each joint in the global coordinate system 

### ISSUE THREAD

**Issue by dchen48** [deepmind/dm_control#420]
We can get the (x, y, z) positions in the global coordinate system by physics.data.geom_xpos. How can we get the the velocity of each joint in the global coordinate system? Thank you for the help.

**Comment by yuvaltassa** [comment]
Like [this](https://github.com/deepmind/dm_control/blob/d6f9cb4e4a616d1e1d3bd8944bc89541434f1d49/dm_control/mujoco/wrapper/core_test.py#L370).

**Comment by dchen48** [comment]
Thanks a lot for the help. Just to make sure, are the position and the velocity with respect to the global coordinate system (i.e., absolute position and absolute velocity)?

**Comment by yuvaltassa** [comment]
Yes.

**Comment by dchen48** [comment]
Thank you!

**Comment by dchen48** [comment]
The coordinates returned by physics.data.geom_xpos seems not to follow the order in the corresponding xml file. For example, in the task reacher, there are 10 geoms. The 10th one is the target. However, the 7th one return by physics.data.geom_xpos is the target. What order does physics.data.geom_xpos follow? Thank you.
