### ISSUE TITLE
Support Mujoco 2.0 ?

### ISSUE THREAD

**Issue by zuoxingdong** [deepmind/dm_control#49]
The recent upgrade of dm_control is really cool especially allowing easier manipulation with Python bindings. Some days ago, Mujoco 2.0 was released and seems like there are quite some changes. Curious to know if there is a roadmap to adapt to Mujoco 2.0 ?

**Comment by alimuldal** [comment]
We are currently working on an update that adds support for MuJoCo 2.0, which should be ready very soon.

**Comment by alimuldal** [comment]
Added support for MuJoCo 2.0 in ae2d628c1437e5cf47211b964fb4039ecb456d46 and 980e02069b23ce97cf0fb4aca339a15bbe3d53d9
