### ISSUE TITLE
Request for acrobot swing up control solution

### ISSUE THREAD

**Issue by rwang0417** [deepmind/dm_control#56]
I'm trying to design a lqr controller along the optimal trajectory of the swing up task for acrobot. But the control solution I got by gradient descending cannot bring the acrobot close enough to the top position for my lqr controller to balance it. I'm wondering if you could provide the control solution for the acrobot swing up task? Thanks a lot!

**Comment by alimuldal** [comment]
The only "solutions" we have are in the form of neural network weights. These aren't something we can easily share with you, and besides, I don't think you would find them very useful in terms of debugging your own code. My advice would be to debug your code on a simpler control domain.
