### ISSUE TITLE
Headless GPU Rendering

### ISSUE THREAD

**Issue by amandlek** [deepmind/dm_control#63]
I'm wondering whether anyone has gotten headless GPU rendering to work. On our Ubuntu machine with a display, the following [script](https://www.dropbox.com/s/56p9wftglyt4dkw/test_dmcontrol.py?dl=0) is able to use the GPU for rendering images, but when running the script headless (i.e. through ssh) we are unable to get it to work with the GPU.

**Comment by alimuldal** [comment]
The GLFW hardware rendering backend requires X11, so it won't work on a headless machine. At the moment your best option is to use software rendering on headless machines, but we are also working on an EGL backend which will allow for hardware rendering on headless machines.

**Comment by amandlek** [comment]
When can we expect the EGL backend to be ready?

**Comment by alimuldal** [comment]
I can't give you an exact timeline, but probably after NeurIPS

**Comment by saran-t** [comment]
I've committed our initial version of headless EGL rendering code now. If you run dm_control on a Linux machine with an Nvidia GPU installed, this should now be the new default backend.

Technical caveat: we normally use "render executors" to ensure that all OpenGL calls occur on a separate, dedicated thread. However, this is currently not working with our open-sourced EGL code. This should not affect you unless you use multiple threads in your program. (If you do, you are responsible for making sure that the `Physics` object is created on the same thread as where `physics.render` is called.)

I have tested this on my own laptop with a GeForce 1050 GTX and it seems to work fine. However, I'd appreciate if people here could also test it out and reply here to say whether it is working for them or not.

If this is causing trouble for you, you can revert to software rendering by setting the environment variable `MUJOCO_GL=osmesa`.

**Comment by amandlek** [comment]
@saran-t Works like a charm on our linux machine. Thanks for the help!

**Comment by KeAWang** [comment]
EGL rendering seems to be causing segfaults on my system. Has anyone else had this issue https://github.com/deepmind/dm_control/issues/70?

**Comment by DanielTakeshi** [comment]
Is EGL considered to be deprecated in favor of OSMesa?
