### ISSUE TITLE
How can I playback trajectories deterministically?

### ISSUE THREAD

**Issue by amandlek** [deepmind/dm_control#65]
@yuvaltassa following up on #64 I tried modifying the script to disable the warmstart - you can find it [here](https://www.dropbox.com/s/dbz8qev8mpm79dv/test_dm_playback.py?dl=0). It still fails from time to time - do you have any additional insight on what might be happening?

I completely agree on your point about training with deterministic dynamics - we would just like the capability to collect demonstrations and replay the actions deterministically to recover the original trajectory.

**Comment by yuvaltassa** [comment]
I'm sorry your script is quite messy. You are definitely not disabling warmstarts, you are just clearing the variable. I _think_ you are resetting to `states[1]`, where `qacc_warmstart` was _not_ 0 (as a step has already been taken) and then setting `qacc_warmstart` to 0. So clearly that would not work.

Please actually _disable warmstarts in the model_ and test again. This means adding 
```xml
<option timestep=".005">
  <flag warmstart="disable"/>
</option>
```
to `humanoid.xml`. I believe your test will pass.

Alternatively you can clean up your script, add some print statements to understand how warmstarting works, and think more carefully about what you are comparing.
