### ISSUE TITLE
Can you indicate which part of code visualize the perturbed force?

### ISSUE THREAD

**Issue by davidsonic** [deepmind/dm_control#68]
Can you indicate which part of code that accomplished the visualization of perturbed force?
I was trying the following approach:
1. define a tendon that connects to sites.
2. One site is at perturb location, and the other is to be determined. 
3. I want to determine another site via information provided by force (3x1) and torque (3x1) in mujoco, still trying. 

Did the code use a better approach? Which part does the job? I looked into viewer module, but still have no idea about which specific snippet did.

**Comment by yuvaltassa** [comment]
Visualising torques is tricky. But assuming you only apply forces, say using the `xfrc_applied` field, you can just put some geom (say capsule) in the worldbody, make it non-colliding and invisible. Then in `Physics.before_step()` you apply the force and in `Physics.after_step()` you make the geom visible and put it in the right place. Below is an annotated code snippet that might be helpful, though your approach of using tendons could work just as well.

```Python
if np.any(perturbation):
      # Position and size of perturbation-visualisation capsule.
      bpos = physics.named.data.xipos[body_name]
      ppos = bpos + force_to_length*perturbation
      physics.named.model.geom_size[caps_name][1] = np.linalg.norm(force_to_length*perturbation)

      # Make visualisation capsule visible.
      physics.named.model.geom_rgba[caps_name][3] = 1

      # Change colour of perturbed body.
      geoms = physics.model.name2id(body_name, 'body') == physics.model.geom_bodyid
      physics.model.geom_rgba[geoms,1] = 0.5

      # Set position / orientation of perturbation-visualisation capsule.
      quat = np.zeros(4)
      mat = np.zeros(9)
      pertnorm = perturbation / np.linalg.norm(perturbation)
      mjlib.mju_quatZ2Vec(quat, pertnorm)
      mjlib.mju_quat2Mat(mat, quat)
      physics.named.data.geom_xpos[caps_name] = ppos
      physics.named.data.geom_xmat[caps_name] = mat
```
