### ISSUE TITLE
Hopper task states and actions?

### ISSUE THREAD

**Issue by KeAWang** [deepmind/dm_control#69]
The hopper task has 4 dimensional actions and 15 dimensional observations. I'm trying to design a cost function for the task, and I'm wondering what each index of the actions and observations corresponds to? In general, how would I find this out?

**Comment by yuvaltassa** [comment]
You can see the actuators in the model's [XML definition](https://github.com/deepmind/dm_control/blob/master/dm_control/suite/hopper.xml#L60) file and the observations in the associated [`get_observation()` function](https://github.com/deepmind/dm_control/blob/master/dm_control/suite/hopper.py#L113) in the domain definition (observations can be task-dependent).
