### ISSUE TITLE
framebuffer error

### ISSUE THREAD

**Issue by Scitator** [deepmind/dm_control#76]
Hi, working with distributed RL algorithms I found quite confusing bug in dm suite:
when it comes to spawning a bunch of environments (like 32/64) dm_suite just goes to 
```
core.py Offscreen framebuffer is not complete, error *****
```

This bug occurs every time when `number of envs` > `number of cpus threads`.
Is there any way to solve it?

**Comment by Scitator** [comment]
UPD: Solved with `MUJOCO_GL="osmesa"`.

**Comment by ogbloomfield** [comment]
I am having the same issue. What was the exact change that you made ?

**Comment by Scitator** [comment]
1. Use instructions from https://github.com/deepmind/dm_control#additional-instructions-for-linux
2. `export MUJOCO_GL="osmesa"` before script
3. now, you can run the script
