### ISSUE TITLE
GLEW initalization error: Missing GL version

### ISSUE THREAD

**Issue by karamarieliu** [deepmind/dm_control#77]
When I run the Quickstart (listed on the main page of dm_control/dm_control/mujoco), I get the above error. I tried following the instructions to install the correct version of libglew but those command error as well (Can't find module libglew2.0). Any tips on how to fix it? I made sure that I have 
 `export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libGLEW.so` in my /.bashrc.

**Comment by alimuldal** [comment]
Can you show the full traceback please?

**Comment by alimuldal** [comment]
I'm closing this since there's not enough information here to diagnose the problem.
