### ISSUE TITLE
On-screen rendering

### ISSUE THREAD

**Issue by amandlek** [deepmind/dm_control#84]
The EGL functionality that you guys added for GPU rendering has been working out for us great, but I'd like to point out a minor issue that we found when trying to use the dm_control viewer - it is necessary to provide the variable `MUJOCO_GL=glfw` whenever we try to run a script that relies on the viewer. This is pretty minor, but just wanted to point it out in case there's a quick fix.

**Comment by alimuldal** [comment]
`MUJOCO_GL=glfw` should no longer be necessary as of 276c6e8ce6dbcb8a037f8aa6a76475db4da41e6a, which made GLFW the default backend instead of EGL
