### ISSUE TITLE
Projection matrix used in the renderer

### ISSUE THREAD

**Issue by Xingyu-Lin** [deepmind/dm_control#85]
Is there a way to easily access the projection matrix for a particular camera in order to convert from world coordinates to screen coordinates?

**Comment by alimuldal** [comment]
Hi,

The [`mjvGLCamera`] struct contains the information you need to derive the OpenGL projection matrix. You can access this via `mujoco.Camera.scene`. For example:
```python
from dm_control import mujoco
from dm_control import suite
from dm_control.mujoco.wrapper.mjbindings import mjlib

env = suite.load(domain_name="humanoid", task_name="run")
cam = mujoco.Camera(env.physics, camera_id=0)
cam.
# Each `mujoco.Camera` has an `mjvScene` struct associated with it...
scene = cam.scene
# ... and each scene has two `mjvGLCamera` structs (for stereoscopic rendering).

# You could either treat the left and right cameras separately, or take their average
# using `mjv_averageCamera`:
average_gl_camera = mjlib.mjv_averageCamera(
    scene.ptr.contents.camera[0],
    scene.ptr.contents.camera[1])

frustum_top = average_gl_camera.frustum_top
frustum_bottom = average_gl_camera.frustum_bottom
 # etc.
```
See [here][projection_matrix] for details on how to derive the `GL_PROJECTION` matrix from these parameters.

[`mjvGLCamera`]: http://mujoco.org/book/APIreference.html#mjvGLCamera
[projection_matrix]: http://www.songho.ca/opengl/gl_projectionmatrix.html
