### ISSUE TITLE
I would very much like to access the implementation of D4PG

### ISSUE THREAD

**Issue by zhaoyingnan179346** [deepmind/dm_control#89]

**Comment by alimuldal** [comment]
`dm_control` is a collection of RL environments, and libraries for designing new environments. We have no plans to release agents as part of this repository - for that you might want to take a look at [TF-agents]. There are also various third-party implementations of D4PG on Github, e.g. https://github.com/msinto93/D4PG.

[TF-agents]: https://github.com/tensorflow/agents
