### ISSUE TITLE
Offscreen framebuffer is not complete

### ISSUE THREAD

**Issue by Gaoee** [deepmind/dm_control#91]
When run the soccer environment, I got the following error
Offscreen framebuffer is not complete, error 0x8cdd.

Maybe it is something about GPU.

**Comment by alimuldal** [comment]
Possible duplicate of #76. Does the OSMesa backend work for you (`MUJOCO_GL=osmesa`, see docs [here][1])?

[1]: https://github.com/deepmind/dm_control#rendering

**Comment by Gaoee** [comment]
Thank you. It works for me.
