### ISSUE TITLE
Step environments in parallel

### ISSUE THREAD

**Issue by theophilee** [deepmind/dm_control#94]
Hi, is there some way to step environments in parallel? Relying on the underlying MjSimPool?

Thanks a lot!

**Comment by alimuldal** [comment]
You can use multiprocessing, e.g. https://github.com/deepmind/dm_control/issues/92#issuecomment-485983854. `MjSimPool` was an OpenAI thing (it looks as though [they eventually decided to remove it](https://github.com/openai/mujoco-py#changelog)).
