### ISSUE TITLE
MuJoCo Soccer environment simulates too slow

### ISSUE THREAD

**Issue by 1576012404** [deepmind/dm_control#98]
here is the time cost when i run  soccer environment for one episode with random actions

 ncalls  tottime  percall  cumtime  percall filename:lineno(function)
   624000    4.216    0.000    7.479    0.000 /home/duo/anaconda3/envs/python36/lib/python3.6/site-packages/dm_control/composer/observation/obs_buffer.py:173(drop_unobserved_upcoming_items)
     4000    1.948    0.000   10.160    0.003 /home/duo/anaconda3/envs/python36/lib/python3.6/site-packages/dm_control/composer/observation/updater.py:176(prepare_for_next_control_step)
  1321880    1.665    0.000    2.627    0.000 /home/duo/anaconda3/envs/python36/lib/python3.6/site-packages/dm_control/mjcf/physics.py:223(_synchronize_from_backing_array)
   272408    1.416    0.000    7.544    0.000 /home/duo/anaconda3/envs/python36/lib/python3.6/site-packages/dm_control/locomotion/walkers/base.py:402(_egocentric)
  1257986    1.410    0.000    1.416    0.000 /home/duo/anaconda3/envs/python36/lib/python3.6/site-packages/dm_control/mjcf/physics.py:556(bind)
   528792    1.021    0.000    1.021    0.000 {built-in method numpy.core.multiarray.dot}
   624468    0.986    0.000    1.929    0.000 /home/duo/anaconda3/envs/python36/lib/python3.6/site-packages/dm_control/composer/observation/obs_buffer.py:118(insert)
     4000    0.980    0.000   19.455    0.005 /home/duo/anaconda3/envs/python36/lib/python3.6/site-packages/dm_control/composer/observation/updater.py:209(update)
  1087996    0.957    0.000    0.961    0.000 {built-in method numpy.core.multiarray.array}
  1321970    0.938    0.000    3.567    0.000 /home/duo/anaconda3/envs/python36/lib/python3.6/site-packages/dm_control/mjcf/physics.py:355(__getattr__)

it seems that the operation of observation costs the most time,why do this?

**Comment by liusiqi43** [comment]
hi, thanks for surfacing this!

We are aware of this issue and we are actively working on improving the performance here as we plan to further scale up the environment! The short answer is that many small Python callbacks seem to incur significant overhead. 

Will update here once we have more to share!
